### ISSUE TITLE
"Dynamically" add CORS/CSP bypasses

### ISSUE THREAD

**Issue by Cynosphere** [moonlight-mod/moonlight#110]
Currently CORS and CSP bypasses are hardcoded into the manifest, which is fine for 99.9% of cases. But there's a 0.1% of cases where there could be configurable URLs.

**Comment by NotNite** [comment]
Not entirely sure how I feel about this, given that because we take the cors list from node-preload into injector, this will have to be an API on moonlightNode. We should probably make a new "moonlightNode but not exposed to web" global, else extensions can set their own CORS/CSP bypasses from within web, which seems very dangerous.

Not sure what we'd call it, but if we do make it, we should probably move moonlightFS into it.

**Comment by NotNite** [comment]
Added with `moonlightNodeSandboxed`. Terrible name!
