### ISSUE TITLE
Manifest: Add `license` field

### ISSUE THREAD

**Issue by Cynosphere** [moonlight-mod/moonlight#29]
We stupidly and blindly blanketed the extension template under AGPL when that wasn't the intention. We should now accommodate for a license field in the manifest and potentially display it in the UI.

(If for some reason this violates AGPL, then I guess we might have to relicense the entire project...)

**Comment by NotNite** [comment]
Due to ✨ infectivity ✨ we will need to relicense the project. I chose AGPL because it means anyone distributing extensions has to include the source, which is overall a net benefit on the community IMO.

If we do relicense, we'd need to pick a new license (MIT? Apache? BSD?), license the extension template under it, and then get all contributors of moonlight to sign off on it.

**Comment by jane0009** [comment]
shouldn't this be closed now due to [cda126a](https://github.com/moonlight-mod/moonlight/commit/cda126acf6a8b99cd548757df97adc443562a641)?
