### ISSUE TITLE
Development versions of extensions with the same id are seemingly ignored

### ISSUE THREAD

**Issue by jane0009** [moonlight-mod/moonlight#38]
not sure if this is true for all extensions or if it's a race condition sort of issue, but when i was working on adding features to the css extension, i ran into an issue where the repo version of the extension was preferred over the development version, even though the development version had a higher semver. to work around it i had to rename the manifest of the dev version to a different name so it would not be counted as the same extension. 

it would be nice if there was a way to choose between a development and repo version of a given extension, or otherwise prefer the version that has the highest version number.

**Comment by NotNite** [comment]
This one's my bad, the entire handling of associating an extension to an installed repository is a *mess*. I really need to rewrite that code in Moonbase/the extension loader.

**Comment by NotNite** [comment]
Also another note here: version parsing doesn't really exist in moonlight? We just compare strings blindly because I wanted to give developers the ability to do whatever with their versions. Not sure how to handle that, so I guess a priority system would be best.

Should it apply per extension or just be a global setting (e.g. a `preferDeveloperExtensions` bool)?

**Comment by NotNite** [comment]
I don't think this happens anymore. Closing.
